services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs,ecr,apigateway
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postech_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres